[features]
seeds = false
skip-lint = false
[programs.localnet]
mycalc = "Ax3Dc6AQqrdY6kLgDpeZwrNCihnAK69HvtMBDyYveALQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/propelius/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
